services:
  livekit:
    image: livekit/livekit-server:v1.7.2
    command: --config /etc/livekit.yaml
    ports:
      - "7880:7880"
      - "7881:7881"
      - "52000-52100:52000-52100/udp"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
